### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by codepunkt** [codepunkt/css-spring#16]
Work in progress

- [x] toPrecision
- [x] getInterpolator
- [x] parseDeclarations
- [x] getAnimationValues
- [x] sanitizeValues
- [x] addInterpolatedValues
- [x] buildKeyframeObject
- [x] main API

**Comment by MariliaMJ** [comment]
I'd like to help in this project! how can I get started?

**Comment by codepunkt** [comment]
@MariliaMJ Thats great to hear, thank you!
This one would be rather hard for newcomers to the project. I'm 80% of my way through it already. There might be another issue you can help with, though.
