### ISSUE TITLE
Add node 8 to travis testing configuration

### ISSUE THREAD

**Issue by codepunkt** [codepunkt/css-spring#31]
Tests should be executed on node 8.x in addition to the currently tested node versions.
This can be done by updating the .travis.yml accordingly.

**Comment by andrejristevski** [comment]
I am working on it

**Comment by codepunkt** [comment]
Small tip: When you write the issue number of the issue that you complete with a pull request in the pull request text - e.g. `Fixes #31`, this should auto-close the issue when the pull request is merged.

Thanks for your help! 👍
