### ISSUE TITLE
Examples don’t work

### ISSUE THREAD

**Issue by zachgibson** [codepunkt/css-spring#35]
Really dig the idea here, but when I tried to get started and run on the examples, nothing was happening?

**Comment by codepunkt** [comment]
Sounds strange. Do you have a minimal reproducible example? What exactly did you do?

**Comment by zachgibson** [comment]
The animation is not playing. [Here’s a CodeSandbox](https://codesandbox.io/s/7215nwlqlj).

**Comment by codepunkt** [comment]
That's because you animate the `left` property on an element that has a static position. No CSS in the world can do that. Try adding `position: relative` to the element with the `animation` 😏
